// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MysqlEfCoreDemo.Data;

#nullable disable

namespace MysqlEfCoreDemo.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250221123425_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MysqlEfCoreDemo.Models.Config", b =>
                {
                    b.Property<string>("config_name")
                        .HasColumnType("longtext");

                    b.Property<string>("config_value")
                        .HasColumnType("longtext");

                    b.Property<string>("delete_flag")
                        .HasColumnType("longtext");

                    b.ToTable("con_mst_tconfig");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.ConnectionModel", b =>
                {
                    b.Property<int>("connection_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("connection_code")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("connection_desc")
                        .HasColumnType("text");

                    b.Property<string>("connection_name")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("connection_status")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("file_password")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("protection_type")
                        .HasColumnType("char(1)");

                    b.Property<byte[]>("source_auth_file_blob")
                        .HasColumnType("blob");

                    b.Property<string>("source_auth_file_name")
                        .HasColumnType("text");

                    b.Property<string>("source_auth_mode")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("source_db_pwd")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("source_db_type")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("source_db_user")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("source_file")
                        .HasColumnType("text");

                    b.Property<string>("source_host_name")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("source_port")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("ssh_auth_mode")
                        .HasColumnType("varchar(128)");

                    b.Property<byte[]>("ssh_file_blob")
                        .HasColumnType("blob");

                    b.Property<string>("ssh_file_name")
                        .HasColumnType("text");

                    b.Property<string>("ssh_host_name")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ssh_port")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("ssh_pwd")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ssh_tunneling")
                        .HasColumnType("char(1)");

                    b.Property<string>("ssh_user")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("connection_gid");

                    b.ToTable("con_mst_tconnection");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.DataSet", b =>
                {
                    b.Property<int>("dataset_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("connector_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("dataset_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("dataset_name")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("module_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("table_name")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("dataset_gid");

                    b.ToTable("con_mst_tdataset");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.DataSetField", b =>
                {
                    b.Property<string>("active_status")
                        .HasColumnType("longtext");

                    b.Property<string>("created_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("dataset_code")
                        .HasColumnType("longtext");

                    b.Property<string>("dataset_field_desc")
                        .HasColumnType("longtext");

                    b.Property<int>("dataset_field_gid")
                        .HasColumnType("int");

                    b.Property<string>("dataset_field_name")
                        .HasColumnType("longtext");

                    b.Property<string>("dataset_field_type")
                        .HasColumnType("longtext");

                    b.Property<string>("dataset_table_field")
                        .HasColumnType("longtext");

                    b.Property<string>("delete_flag")
                        .HasColumnType("longtext");

                    b.Property<string>("field_mandatory")
                        .HasColumnType("longtext");

                    b.Property<string>("updated_by")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.ToTable("con_mst_tdataset_field");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.DataSetImport", b =>
                {
                    b.Property<int>("dataset_import_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("dataset_info")
                        .HasColumnType("text");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<int>("job_gid")
                        .HasColumnType("int(11)");

                    b.Property<string>("pipelinecode")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("remarks")
                        .HasColumnType("text");

                    b.Property<string>("status_code")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("dataset_import_gid");

                    b.ToTable("con_trn_tdatasetimport");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.Master", b =>
                {
                    b.Property<long>("master_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("delete_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("depend_code")
                        .HasColumnType("varchar(50)");

                    b.Property<long>("depend_gid")
                        .HasColumnType("bigint(20)");

                    b.Property<string>("master_code")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("master_name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("parent_code")
                        .HasColumnType("varchar(50)");

                    b.Property<long>("parent_gid")
                        .HasColumnType("bigint(20)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("master_gid");

                    b.ToTable("con_mst_tmaster");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.Pipeline", b =>
                {
                    b.Property<int>("pipeline_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("connection_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("db_name")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("pipeline_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("pipeline_desc")
                        .HasColumnType("text");

                    b.Property<string>("pipeline_name")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("pipeline_status")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("sheet_name")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("source_file_name")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("table_view_query_desc")
                        .HasColumnType("text");

                    b.Property<string>("table_view_query_type")
                        .HasColumnType("char(1)");

                    b.Property<string>("target_dataset_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("pipeline_gid");

                    b.ToTable("con_mst_tpipeline");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.PipelineApiCsvHeader", b =>
                {
                    b.Property<int>("api_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("api_jsonvalue")
                        .HasColumnType("TEXT");

                    b.Property<string>("api_key")
                        .HasColumnType("TEXT");

                    b.Property<string>("api_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("created_date")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("pipeline_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("remarks")
                        .HasColumnType("TEXT");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("updated_date")
                        .HasColumnType("varchar(32)");

                    b.HasKey("api_gid");

                    b.ToTable("con_trn_tapi");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.PipelineCondition", b =>
                {
                    b.Property<int>("pplcondition_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("condition_msg")
                        .HasColumnType("text");

                    b.Property<string>("condition_name")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("condition_text")
                        .HasColumnType("text");

                    b.Property<string>("condition_type")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("pipeline_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("sys_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("pplcondition_gid");

                    b.ToTable("con_trn_tpplcondition");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.PipelineCsvHeader", b =>
                {
                    b.Property<int>("pplcsvheader_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("column_separator")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("csvfile_dateformat")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("csvfile_datetimeformat")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<int>("number_ofcolumns")
                        .HasColumnType("int(11)");

                    b.Property<int>("number_oflines_toskip")
                        .HasColumnType("int(11)");

                    b.Property<string>("pipeline_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("pplcsvheader_gid");

                    b.ToTable("con_trn_tpplcsvheader");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.PipelineFinalization", b =>
                {
                    b.Property<int>("finalization_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("cron_expression")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("error_mode")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("extract_condition")
                        .HasColumnType("text");

                    b.Property<string>("extract_mode")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("key_field")
                        .HasColumnType("text");

                    b.Property<string>("last_incremental_val")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("parent_dataset_code")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("pipeline_code")
                        .HasColumnType("varchar(32)");

                    b.Property<int>("pull_days")
                        .HasColumnType("int");

                    b.Property<string>("reject_duplicate_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("run_type")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("upload_mode")
                        .HasColumnType("varchar(64)");

                    b.HasKey("finalization_gid");

                    b.ToTable("con_trn_tpplfinalization");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.PipelineIncrementalRecord", b =>
                {
                    b.Property<int>("incremental_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("incremental_field")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("incremental_value")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("pipeline_code")
                        .HasColumnType("varchar(32)");

                    b.HasKey("incremental_gid");

                    b.ToTable("con_trn_tincrementalrecord");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.PipelineMapping", b =>
                {
                    b.Property<int>("pplfieldmapping_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("dataset_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("dataset_field_name")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("default_value")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("pipeline_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ppl_field_name")
                        .HasColumnType("varchar(128)");

                    b.Property<int>("pplfieldmapping_flag")
                        .HasColumnType("boolean");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("pplfieldmapping_gid");

                    b.ToTable("con_trn_tpplfieldmapping");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.PipelineSourcefield", b =>
                {
                    b.Property<int>("pplsourcefield_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cast_dataset_table_field")
                        .HasColumnType("text");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("dataset_table_field")
                        .HasColumnType("varchar(128)");

                    b.Property<int>("dataset_table_field_sno")
                        .HasColumnType("int(11)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("expressionfield_json")
                        .HasColumnType("json");

                    b.Property<string>("pipeline_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("source_type")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("sourcefield_datatype")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("sourcefield_expression")
                        .HasColumnType("text");

                    b.Property<string>("sourcefield_name")
                        .HasColumnType("varchar(128)");

                    b.Property<int>("sourcefield_sno")
                        .HasColumnType("int(11)");

                    b.Property<string>("sourcefieldmapping_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("pplsourcefield_gid");

                    b.ToTable("con_trn_tpplsourcefield");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.QCDMaster", b =>
                {
                    b.Property<int>("master_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("active_status")
                        .HasColumnType("char(1)");

                    b.Property<string>("created_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("depend_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("depend_master_syscode")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("depend_parent_master_syscode")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("master_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("master_multiple_name")
                        .HasColumnType("text");

                    b.Property<string>("master_name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("master_short_code")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("master_syscode")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("parent_master_syscode")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("system_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("master_gid");

                    b.ToTable("con_mst_tqcdmaster");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.Scheduler", b =>
                {
                    b.Property<int>("scheduler_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("additional_status")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("delete_flag")
                        .HasColumnType("char(1)");

                    b.Property<string>("file_name")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("file_path")
                        .HasColumnType("text");

                    b.Property<DateTime>("last_update_date")
                        .HasColumnType("datetime");

                    b.Property<string>("pipeline_code")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("scheduled_date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("scheduler_end_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("scheduler_initiated_by")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("scheduler_parameters")
                        .HasColumnType("text");

                    b.Property<string>("scheduler_remark")
                        .HasColumnType("text");

                    b.Property<DateTime>("scheduler_start_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("scheduler_status")
                        .HasColumnType("varchar(32)");

                    b.HasKey("scheduler_gid");

                    b.ToTable("con_trn_tscheduler");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.columnDatatype", b =>
                {
                    b.Property<string>("dataset_code")
                        .HasColumnType("longtext");

                    b.Property<string>("dataset_field_name")
                        .HasColumnType("longtext");

                    b.Property<string>("dataset_field_type")
                        .HasColumnType("longtext");

                    b.Property<string>("pipeline_code")
                        .HasColumnType("longtext");

                    b.Property<string>("source_type")
                        .HasColumnType("longtext");

                    b.Property<string>("sourcefield_name")
                        .HasColumnType("longtext");

                    b.ToTable("con_col_datatype");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.dataProcessing", b =>
                {
                    b.Property<long>("dataprocessing_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("dataprocessing_child_master_gid")
                        .HasColumnType("bigint");

                    b.Property<int>("dataprocessing_header_gid")
                        .HasColumnType("int(11)");

                    b.Property<long>("dataprocessing_master_gid")
                        .HasColumnType("bigint");

                    b.Property<int>("dataprocessing_orderby")
                        .HasColumnType("int(11)");

                    b.Property<string>("dataprocessing_param1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("dataprocessing_param2")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("dataprocessing_param3")
                        .HasColumnType("varchar(50)");

                    b.Property<long>("dataprocessing_parent_master_gid")
                        .HasColumnType("bigint");

                    b.Property<int>("dataprocessing_pipeline_gid")
                        .HasColumnType("int(11)");

                    b.Property<int>("dataprocessing_pplfieldmapping_gid")
                        .HasColumnType("int(11)");

                    b.Property<string>("delete_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("dataprocessing_gid");

                    b.ToTable("con_mst_tdataprocessing");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.dataProcessingheader", b =>
                {
                    b.Property<long>("dataprocessingheader_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("dataprocessingheader_pipeline_code")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("dataprocessingheader_ppl_field_name")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<long>("dataprocessingheader_pplfieldmapping_gid")
                        .HasColumnType("bigint(20)");

                    b.Property<int>("dataprocessingheader_seqno")
                        .HasColumnType("int(11)");

                    b.Property<string>("delete_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("dataprocessingheader_gid");

                    b.ToTable("con_mst_tdataprocessingheader");
                });

            modelBuilder.Entity("MysqlEfCoreDemo.Models.fieldConfig", b =>
                {
                    b.Property<long>("fieldconfig_gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("delete_flag")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("fieldconfig_dynamicfields")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("fieldconfig_expression_label")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("fieldconfig_expressions")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("fieldconfig_master_code")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("updated_by")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("fieldconfig_gid");

                    b.ToTable("con_mst_tfieldconfig");
                });
#pragma warning restore 612, 618
        }
    }
}
