using Microsoft.Graph.Models;
using Microsoft.Kiota.Abstractions;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MysqlEfCoreDemo.Models
{
    public class Transaction
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int tran_gid { get; set; }
        public int file_gid { get; set; }
        public int recon_gid { get; set; }
        public string acc_code { get; set; }
        [NotMapped]
        public Date tran_date { get; set; }
        public decimal tran_value { get; set; }
        public decimal excp_value { get; set; }
        public decimal mapped_value { get; set; }
        public string tran_acc_mode { get; set; }
        public string tran_mult { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public string col3 { get; set; }
        public string col4 { get; set; }
        public string col5 { get; set; }
        public string col6 { get; set; }
        public string col7 { get; set; }
        public string col8 { get; set; }
        public string col9 { get; set; }
        public string col10 { get; set; }
        public string col11 { get; set; }
        public string col12 { get; set; }
        public string col13 { get; set; }
        public string col14 { get; set; }
        public string col15 { get; set; }
        public string col16 { get; set; }
        public string col17 { get; set; }
        public string col18 { get; set; }
        public string col19 { get; set; }
        public string col20 { get; set; }
        public string col21 { get; set; }
        public string col22 { get; set; }
        public string col23 { get; set; }
        public string col24 { get; set; }
        public string col25 { get; set; }
        public string col26 { get; set; }
        public string col27 { get; set; }
        public string col28 { get; set; }
        public string col29 { get; set; }
        public string col30 { get; set; }
        public string col31 { get; set; }
        public string col32 { get; set; }
        public string col33 { get; set; }
        public string col34 { get; set; }
        public string col35 { get; set; }
        public string col36 { get; set; }
        public string col37 { get; set; }
        public string col38 { get; set; }
        public string col39 { get; set; }
        public string col40 { get; set; }
        public string col41 { get; set; }
        public string col42 { get; set; }
        public string col43 { get; set; }
        public string col44 { get; set; }
        public string col45 { get; set; }
        public string col46 { get; set; }
        public string col47 { get; set; }
        public string col48 { get; set; }
        public string col49 { get; set; }
        public string col50 { get; set; }
        public string col51 { get; set; }
        public string col52 { get; set; }
        public string col53 { get; set; }
        public string col54 { get; set; }
        public string col55 { get; set; }
        public string col56 { get; set; }
        public string col57 { get; set; }
        public string col58 { get; set; }
        public string col59 { get; set; }
        public string col60 { get; set; }
        public string col61 { get; set; }
        public string col62 { get; set; }
        public string col63 { get; set; }
        public string col64 { get; set; }
        public string col65 { get; set; }
        public string col66 { get; set; }
        public string col67 { get; set; }
        public string col68 { get; set; }
        public string col69 { get; set; }
        public string col70 { get; set; }
        public string col71 { get; set; }
        public string col72 { get; set; }
        public string col73 { get; set; }
        public string col74 { get; set; }
        public string col75 { get; set; }
        public string col76 { get; set; }
        public string col77 { get; set; }
        public string col78 { get; set; }
        public string col79 { get; set; }
        public string col80 { get; set; }
        public string col81 { get; set; }
        public string col82 { get; set; }
        public string col83 { get; set; }
        public string col84 { get; set; }
        public string col85 { get; set; }
        public string col86 { get; set; }
        public string col87 { get; set; }
        public string col88 { get; set; }
        public string col89 { get; set; }
        public string col90 { get; set; }
        public string col91 { get; set; }
        public string col92 { get; set; }
        public string col93 { get; set; }
        public string col94 { get; set; }
        public string col95 { get; set; }
        public string col96 { get; set; }
        public string col97 { get; set; }
        public string col98 { get; set; }
        public string col99 { get; set; }
        public string col100 { get; set; }
        public string col101 { get; set; }
        public string col102 { get; set; }
        public string col103 { get; set; }
        public string col104 { get; set; }
        public string col105 { get; set; }
        public string col106 { get; set; }
        public string col107 { get; set; }
        public string col108 { get; set; }
        public string col109 { get; set; }
        public string col110 { get; set; }
        public string col111 { get; set; }
        public string col112 { get; set; }
        public string col113 { get; set; }
        public string col114 { get; set; }
        public string col115 { get; set; }
        public string col116 { get; set; }
        public string col117 { get; set; }
        public string col118 { get; set; }
        public string col119 { get; set; }
        public string col120 { get; set; }
        public string col121 { get; set; }
        public string col122 { get; set; }
        public string col123 { get; set; }
        public string col124 { get; set; }
        public string col125 { get; set; }
        public string col126 { get; set; }
        public string col127 { get; set; }
        public string col128 { get; set; }
        public string tran_remark1 { get; set; }
        public string tran_remark2 { get; set; }
        public int ko_gid { get; set; }
        [NotMapped]
        public Date ko_date { get; set; }
        public string delete_flag { get; set; }
    }
    public class Balance
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int accbal_gid { get; set; }
        public string file_gid { get; set; }
        public string acc_code { get; set; }
        [NotMapped]
        public Date tran_date { get; set; }
        public double bal_value { get; set; }
        public DateTime insert_date { get; set; }
        public string insert_by { get; set; }
        public DateTime update_date { get; set; }
        public string update_by { get; set; }
        public string delete_flag { get; set; }

    }

    public class Bulkcopytran
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int bcptran_gid { get; set; }
        public int file_gid { get; set; }
        public int rec_slno { get; set; }
        public string acc_code { get; set; }
        [NotMapped]
        public Date tran_date { get; set; }
        public double tran_value { get; set; }
        public int tran_mult { get; set; }
        public string tran_acc_mode { get; set; }
        public string tran_value_type { get; set; }
        public string value_acc_mode { get; set; }
        public double value_debit { get; set; }
        public double value_credit { get; set; }
        public double value_signed { get; set; }
        public double value_reverse_signed { get; set; }
        public string bal_value_flag { get; set; }
        public string bal_value_type { get; set; }
        public double bal_value_debit { get; set; }
        public double bal_value_credit { get; set; }
        public double bal_value_signed { get; set; }
        public double bal_value_reverse_signed { get; set; }
        public double bal_value { get; set; }
        public int bal_mult { get; set; }
        public string bal_acc_mode { get; set; }
        public int tran_gid { get; set; }
        public int match_gid { get; set; }
        public decimal ko_value { get; set; }
        public string ko_acc_mode { get; set; }
        public string ko_reason { get; set; }
        public int tranbrkp_gid { get; set; }
        public decimal tranbrkp_value { get; set; }
        public string tranbrkp_acc_mode { get; set; }
        public string tranbrkp_reason { get;set; }
        public int tranbrkptype_gid { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public string col3 { get; set; }
        public string col4 { get; set; }
        public string col5 { get; set; }
        public string col6 { get; set; }
        public string col7 { get; set; }
        public string col8 { get; set; }
        public string col9 { get; set; }
        public string col10 { get; set; }
        public string col11 { get; set; }
        public string col12 { get; set; }
        public string col13 { get; set; }
        public string col14 { get; set; }
        public string col15 { get; set; }
        public string col16 { get; set; }
        public string col17 { get; set; }
        public string col18 { get; set; }
        public string col19 { get; set; }
        public string col20 { get; set; }
        public string col21 { get; set; }
        public string col22 { get; set; }
        public string col23 { get; set; }
        public string col24 { get; set; }
        public string col25 { get; set; }
        public string col26 { get; set; }
        public string col27 { get; set; }
        public string col28 { get; set; }
        public string col29 { get; set; }
        public string col30 { get; set; }
        public string col31 { get; set; }
        public string col32 { get; set; }
        public string col33 { get; set; }
        public string col34 { get; set; }
        public string col35 { get; set; }
        public string col36 { get; set; }
        public string col37 { get; set; }
        public string col38 { get; set; }
        public string col39 { get; set; }
        public string col40 { get; set; }
        public string col41 { get; set; }
        public string col42 { get; set; }
        public string col43 { get; set; }
        public string col44 { get; set; }
        public string col45 { get; set; }
        public string col46 { get; set; }
        public string col47 { get; set; }
        public string col48 { get; set; }
        public string col49 { get; set; }
        public string col50 { get; set; }
        public string col51 { get; set; }
        public string col52 { get; set; }
        public string col53 { get; set; }
        public string col54 { get; set; }
        public string col55 { get; set; }
        public string col56 { get; set; }
        public string col57 { get; set; }
        public string col58 { get; set; }
        public string col59 { get; set; }
        public string col60 { get; set; }
        public string col61 { get; set; }
        public string col62 { get; set; }
        public string col63 { get; set; }
        public string col64 { get; set; }
        public string col65 { get; set; }
        public string col66 { get; set; }
        public string col67 { get; set; }
        public string col68 { get; set; }
        public string col69 { get; set; }
        public string col70 { get; set; }
        public string col71 { get; set; }
        public string col72 { get; set; }
        public string col73 { get; set; }
        public string col74 { get; set; }
        public string col75 { get; set; }
        public string col76 { get; set; }
        public string col77 { get; set; }
        public string col78 { get; set; }
        public string col79 { get; set; }
        public string col80 { get; set; }
        public string col81 { get; set; }
        public string col82 { get; set; }
        public string col83 { get; set; }
        public string col84 { get; set; }
        public string col85 { get; set; }
        public string col86 { get; set; }
        public string col87 { get; set; }
        public string col88 { get; set; }
        public string col89 { get; set; }
        public string col90 { get; set; }
        public string col91 { get; set; }
        public string col92 { get; set; }
        public string col93 { get; set; }
        public string col94 { get; set; }
        public string col95 { get; set; }
        public string col96 { get; set; }
        public string col97 { get; set; }
        public string col98 { get; set; }
        public string col99 { get; set; }
        public string col100 { get; set; }
        public string col101 { get; set; }
        public string col102 { get; set; }
        public string col103 { get; set; }
        public string col104 { get; set; }
        public string col105 { get; set; }
        public string col106 { get; set; }
        public string col107 { get; set; }
        public string col108 { get; set; }
        public string col109 { get; set; }
        public string col110 { get; set; }
        public string col111 { get; set; }
        public string col112 { get; set; }
        public string col113 { get; set; }
        public string col114 { get; set; }
        public string col115 { get; set; }
        public string col116 { get; set; }
        public string col117 { get; set; }
        public string col118 { get; set; }
        public string col119 { get; set; }
        public string col120 { get; set; }
        public string col121 { get; set; }
        public string col122 { get; set; }
        public string col123 { get; set; }
        public string col124 { get; set; }
        public string col125 { get; set; }
        public string col126 { get; set; }
        public string col127 { get; set; }
        public string col128 { get; set; }
        public string valid_flag { get; set; }
        public string reject_reason { get; set; }
        public string delete_flag { get; set; }
    }
}
